services:
  db:
    image: mysql:8.0
    container_name: okanefy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    networks:
      - okanefy_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./okanefy_api
    container_name: okanefy_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - okanefy_network
      
  frontend:
    build: ./okanefy_frontend
    container_name: okanefy_frontend
    restart: always
    env_file:
      - ./okanefy_frontend/.env
    ports:
      - "5173:5173"
    networks:
      - okanefy_network

volumes:
  mysql_data:

networks:   
  okanefy_network:
    driver: bridge
